# --- Hugo .Site.Params are all in this yaml -----------------------------------
copyright: Mr MXF Ltd.
privacy_policy: /privacy
contact: /contact
time_format_blog: 2006-01-02

gdpr:
  owner: MrMXF Ltd
  email: info@mrmxf.com

# --- libraries loaded in partial scripts.html -----------------------------------
mermaid:
  enable: true
plantuml:
  enable: false
markmap:
  enable: false
katex:
  enable: false

# --- taxonomy -----------------------------------------------------------------
taxonomy:
# set taxonomyCloud: [] to hide taxonomy clouds
taxonomyCloud:
  - tags
  - categories
# If used, must have same length as taxonomyCloud
taxonomyCloudTitle:
  - Tags
  - Categories
# set taxonomyPageHeader: [] to hide taxonomies on the page headers
taxonomyPageHeader:
  - tags
  - categories

# --- Highlighting -------------------------------------------------------------
pygmentsCodeFences: true
pygmentsUseClasses: false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic: false
#pygmentsOptions: "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle: "tango"

# --- site images --------------------------------------------------------------
# First one is picked as the Twitter card image if not set on page.
images: ["/img/logo-otsg.png"]

# --- is archived --------------------------------------------------------------
# Flag used to decide whether this is an archived version of the site and so
# display a banner on every page indicating that this is an archived version of
# the docs. Set this flag to "true" if you want to display the banner.
site_is_archived: false

# --- jumbo --------------------------------------------------------------------
# Menu title if your navbar has a jumbo selector to access .Site defined links.
# This menu appears only if you have at least one [params.jumbo] set.
#jumbo_menu_text: Software

# The jumbo selector is a categorised array number for the version of the docs represented in this doc set.
# Used in the "version-banner" partial to display a version number for the
# current doc set.
No_jumbo:
  - category: mrx-tool
    items:
    - item: "@latest"
      url:  https://github.com/metarex-media/mrx-tool
      icon: cloud download alternate icon
    - item: "α alpha"
      url:  https://github.com/metarex-media/mrx-tool/tree/3ab19f0c1e558e1f57467461abf75fb1f849d5fd
  - category: mrx-demo
    items:
    - item: "@latest"
      url:  https://github.com/metarex-media/mrx-demo
      icon: cloud download alternate icon
    - item: "α alpha"
      url:  https://github.com/metarex-media/mrx-demo/tree/c6a28748f33be2db752fc73951de5b7ddc0033d8

# A link to latest version of the docs. Used in the "version-banner" partial to
# point people to the main doc site.
url_latest_version: https://opentsg.io

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo: https://github.com/mrmxf/opentsg-website
# An optional link to a related project repo. For example, the sibling repository where your product code lives.
github_project_repo: https://github.com/mrmxf

# Specify a value here if your content directory is not in your repo's root directory
# github_subdir: ""

# Uncomment this if your GitHub repo does not have "main" as the default branch,
# or specify a new value if you want to reference another branch in your GitHub links
github_branch: main

# Google Custom Search Engine ID. Remove or comment out to disable search.
# gcs_engine_id: "d72aa9b2712488cc3"

# Enable Algolia DocSearch
algolia_docsearch: false

# Enable Lunr.js offline search
offlineSearch: false

# Enable syntax highlighting and copy buttons on code blocks with Prism
prism_syntax_highlighting: true

# --- UI -----------------------------------------------------------------------
ui:
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable: false
# Set to true to disable the About link in the site footer
footer_about_disable: true
# Set to false if you don't want to display a logo (/static/brand/logo.svg) in the top navbar
navbar_logo: true
# Set to true if you don't want the top navbar to be translucent when over a `block/cover`, like on the homepage.
navbar_translucent_over_cover_disable: false
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact: false
# Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable: true

# --- Feedback -----------------------------------------------------------------
# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
feedback:
  enable: true
  # The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
  yes: "Glad to hear it! Please <a href='https://github.com/mrmxf/opentsg-website/issues/new'>tell us how we can improve</a>."
  no: "Sorry to hear that. Please <a href='https://github.com/mrmxf/opentsg-website/issues/new'>tell us how we can improve</a>."

# --- Reading time -------------------------------------------------------------
# Adds a reading time to the top of each doc.
# If you want this feature, but occasionally need to remove the Reading time from a single page,
# add "hide_readingtime: true" to the page's front matter
readingtime:
  enable: true

# End user relevant links. These will show up on left side of footer and in the community page if you have one.
links:
user:
  # - name: Newsletter
  #   url: /contact
  #   icon: fa fa-envelope
  #   desc: Discussion and help from your fellow users
  # - name: Discord
  #   url: https://discord.gg/uBxZXYZARw
  #   icon: "fab fa-discord"
  #   desc: "Join #metarex.media on Discord to give us your thoughts!"

#   - name: "Stack Overflow"
#     url: "https://example.org/stack"
#     icon: "fab fa-stack-overflow"
#     desc: "Practical questions and curated answers"

# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
developer:
  - name: GitHub
    url: https://github.com/mrmxf/opentsg-website
    icon: fab fa-github
    desc: Development takes place here!
#   - name: "Slack"
#     url: "https://example.org/slack"
#     icon: "fab fa-slack"
#     desc: "Chat with other project developers"
#   - name: "Developer mailing list"
#     url: "https://example.org/mail"
#     icon: "fa fa-envelope"
#     desc: "Discuss development issues around the project"

# Site relevant links. These will show up on right side of footer and in the community page if you have one.
site:
  - name: Privacy Policy
    url: docs/reference/project/privacy/
    icon: "fab fa-user-shield"
    desc: "metarex.media privacy policy"

history:
  - date: "2024-01-17"
    version: "v0.2.0"
    release: "hackathon update"
